Initial repo README
redhat-eets/cp4na pull request #78
Opened 2023-05-24 13:33 UTC by g2github

2023-05-26 17:05 UTC, agopala95 commented on README.md
> + [https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.4/html/clusters/managing-your-clusters#enable-cim](CIM)  \
The CIM link seems to be broken here.

2023-05-26 17:09 UTC, agopala95 commented on README.md
> +[https://github.com/redhat-eets/cp4na/blob/main/ansible/openshift_gitops_install.yaml](https://github.com/redhat-eets/cp4na/blob/main/ansible/openshift_gitops_install.yaml)
The "\" seems to persist here at the end of the line.

2023-05-26 17:19 UTC, agopala95 commented on README.md
> +c. cp-console.apps.Hub /<cluster name/>.FQDN
Line 39 seems to render incorrectly.

```suggestion
c. cp-console.apps.\<Hub cluster name>.\<FQDN>
```

2023-05-26 17:21 UTC, agopala95 commented on README.md
> +3. Install the necessary prerequisites needed for the CP4NA’s siteplanner component to deploy OCP SNO with RHACM and ArgoCD in conjunction. The following installations are taken care of by the ansibl
The backward slash seems to persist at the end of line 41. 
```suggestion
3. Install the necessary prerequisites needed for the CP4NA’s siteplanner component to deploy OCP SNO with RHACM and ArgoCD in conjunction. The following installations are taken care of by the ansible playbook linked below:- 
```

2023-05-26 17:47 UTC, agopala95 commented on README.md
> +Command to get the CP4NA GUI url link \
Just a lingering backward slash. 
```suggestion
Command to get the CP4NA GUI url link -
```

2023-05-26 17:53 UTC, agopala95 commented on README.md
> +![alt_text](Reference_Images/cp4na-access-ctl-2.png "image_tooltip")
One of the images seem to have been skipped here in between lines 110 and 112.

2023-05-26 17:54 UTC, agopala95 commented on README.md
> +Automation Administrator, SLMAdmin and SPAdmin are the roles to be chosen. \
```suggestion
Automation Administrator, SLMAdmin and SPAdmin are the roles to be chosen. 
```

2023-05-26 17:56 UTC, agopala95 commented on README.md
> +![alt_text](../cp4na/Reference_Images/cp4na-admin-4.png "image_tooltip")
Image does not seem to render here. The image in line 120 needs to be above this one.

2023-05-26 17:58 UTC, agopala95 commented on README.md
> +5. Next, generate and take note of the API key for the user “admin” as seen in the screenshots below
```suggestion
6. Next, generate and take note of the API key for the user “admin” as seen in the screenshots below
```

2023-05-26 18:06 UTC, agopala95 commented on README.md
> +auth_address: CP4NA SiteplannerGUI url + <em>icp4d-api/v1/authorize \
Seems to be some kind of syntax issue. 
```suggestion
auth_address: CP4NA SiteplannerGUI url + icp4d-api/v1/authorize 
```

2023-05-26 18:06 UTC, agopala95 commented on README.md
> +Next, export the file path as LMCONFIG \
```suggestion
Next, export the file path as LMCONFIG 
```

2023-05-26 18:06 UTC, agopala95 commented on README.md
> +export LMCONFIG=/home/openshift/lmctl.yaml \
```suggestion
export LMCONFIG=/home/openshift/lmctl.yaml 
```

2023-05-26 18:07 UTC, agopala95 commented on README.md
> +[https://github.com/IBM/lmctl/blob/master/docs/getting-started.md](https://github.com/IBM/lmctl/blob/master/docs/getting-started.md) \
```suggestion
[https://github.com/IBM/lmctl/blob/master/docs/getting-started.md](https://github.com/IBM/lmctl/blob/master/docs/getting-started.md) 
```

2023-05-26 18:08 UTC, agopala95 commented on README.md
> +python3 -m pip install lmctl \
```suggestion
python3 -m pip install lmctl 
```

2023-05-26 18:09 UTC, agopala95 commented on README.md
> +Add resource driver through lmctl \
```suggestion
Add resource driver through lmctl 
```

2023-05-26 18:09 UTC, agopala95 commented on README.md
> +\
```suggestion

```

2023-05-26 18:10 UTC, agopala95 commented on README.md
> +lmctl resourcedriver add --type ansible --url https://ansible-lifecycle-driver:8293 dev --certificate ald-tls.pem \
```suggestion
lmctl resourcedriver add --type ansible --url https://ansible-lifecycle-driver:8293 dev --certificate ald-tls.pem 
```

2023-05-26 18:11 UTC, agopala95 commented on README.md
> +Files having commented out lines or appended lines- \
```suggestion
Files having commented out lines or appended lines- 
```

2023-05-26 18:11 UTC, agopala95 commented on README.md
> +\
```suggestion

```

2023-05-26 18:12 UTC, agopala95 commented on README.md
> +[openshift@dhcpserver ocp-cluster-automation-develop]$ lmctl project push dev<em>
The <em> seems to stick out while rendering.

2023-05-26 18:18 UTC, agopala95 commented on README.md
> +![alt_text](Reference_Images/cp4na-cpr-prov-8.png "image_tooltip")
The image here seems to be of the CreateDeviceRole_Provisioner screenshot. This needs to be replaced with the CreateDeviceType_SuperMicro image.

2023-05-26 18:21 UTC, agopala95 commented on README.md
> +![alt_text](Reference_Images/cp4na-cd-prov-10.png "image_tooltip")
The image here seems to be that of CreateSite_Westford API call. This needs to be replaced with the CreateDevice_Provisioner image.

2023-05-26 18:22 UTC, agopala95 commented on README.md
> +i) Body for DNS DHCP Server: \
```suggestion
i) Body for DNS DHCP Server: 
```

2023-05-26 18:22 UTC, agopala95 commented on README.md
> +\
```suggestion

```

2023-05-26 18:24 UTC, agopala95 commented on README.md
> +- host: IP address of the server hosting the DNS/DHCP service \
```suggestion
- host: IP address of the server hosting the DNS/DHCP service 
```

2023-05-26 18:24 UTC, agopala95 commented on README.md
> +- user: server login username`
```suggestion
- user: server login username
```

2023-05-26 18:24 UTC, agopala95 commented on README.md
> +- dhcp_file: file to be referred to check the DHCP configuration`
```suggestion
- dhcp_file: file to be referred to check the DHCP configuration
```

2023-05-26 18:26 UTC, agopala95 commented on README.md
> +The user can note that the body has the config context field with key/value fields within it which includes the values as follows: \
```suggestion
The user can note that the body has the config context field with key/value fields within it which includes the values as follows: 
```

2023-05-26 18:26 UTC, agopala95 commented on README.md
> +- host: IP address of the server acting as the provisioning host. \
```suggestion
- host: IP address of the server acting as the provisioning host. 
```

2023-05-26 18:26 UTC, agopala95 commented on README.md
> +- user: server login username`
```suggestion
- user: server login username
```

2023-05-26 18:34 UTC, agopala95 commented on README.md
> + "is_active": **true**,
The bold effect does not seem to render here. A way to get this working would be to replace ```yaml - ``` with <pre> and </pre>

2023-05-26 18:36 UTC, agopala95 commented on README.md
> +![alt_text](Reference_images/cp4na-cs-ipmi-svc-14.png "image_tooltip")
Image does not seem to render here. If the image is present, maybe once it gets merged it might work?

2023-05-26 18:37 UTC, agopala95 commented on README.md
> +k. The final data to be uploaded is the automation context data which contains a JQuery needed for SNO deployment. This can be done by executing the **CreateAutomationContext API request.
```suggestion
k. The final data to be uploaded is the automation context data which contains a JQuery needed for SNO deployment. This can be done by executing the **CreateAutomationContext** API request.
```

2023-05-26 18:39 UTC, agopala95 commented on README.md
> +10.  Now that the required data has been modeled into the SitePlanner, SNO deployment is ready to be executed. This is done by doing a “build Site” action either through the CP4NA UI or the REST API
```suggestion

10.  Now that the required data has been modeled into the SitePlanner, SNO deployment is ready to be executed. This is done by doing a “build Site” action either through the CP4NA UI or the REST API request **BuildSite**.
```

2023-05-26 18:45 UTC, agopala95 commented on README.md
>  }
After the bracket, the yaml closing character ``` might have been missed here.

2023-05-26 18:45 UTC, agopala95 commented on README.md
>  }
After the bracket, the yaml closing character ``` might have been missed here.

2023-05-26 18:46 UTC, agopala95 requested changes
Apart from a few issues with syntax, the readme looks good.

2023-05-30 12:16 UTC, g2github commented on README.md
> + [https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.4/html/clusters/managing-your-clusters#enable-cim](CIM)  \
CIM links appears to work for me.

2023-05-30 13:39 UTC, g2github commented on README.md
> +[https://github.com/redhat-eets/cp4na/blob/main/ansible/openshift_gitops_install.yaml](https://github.com/redhat-eets/cp4na/blob/main/ansible/openshift_gitops_install.yaml)
Change made

2023-05-30 13:40 UTC, g2github commented on README.md
> +c. cp-console.apps.Hub /<cluster name/>.FQDN
Change made

2023-05-30 15:40 UTC, agopala95 commented on README.md
> + [https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.4/html/clusters/managing-your-clusters#enable-cim](CIM)  \
Are you able to go to this link when doing a preview of the file on Github?

2023-05-30 15:43 UTC, agopala95 commented on README.md
> +\
```suggestion

```

2023-05-30 15:51 UTC, agopala95 commented on README.md
```suggestion
![alt_text](Reference_Images/cp4na-admin-4.png "image_tooltip")
```

2023-05-30 15:54 UTC, agopala95 commented on README.md
Image for the generate API key for the admin user through the CP4NA GUI can be inserted here.

2023-05-30 16:00 UTC, agopala95 commented on README.md
> +![alt_text](Reference_images/cp4na-cs-ipmi-svc-14.png "image_tooltip")
```suggestion
![alt_text](Reference_Images/cp4na-cs-ipmi-svc-14.png "image_tooltip")
```

2023-05-30 16:02 UTC, agopala95 commented on README.md
> +- The object_type field represents the Site type **dcim.type**
```suggestion
- The object_type field represents the Site type **dcim.site**
```

2023-05-30 21:08 UTC, g2github commented on README.md
> +![alt_text](Reference_Images/cp4na-cpr-prov-8.png "image_tooltip")
Fixed

2023-05-30 21:08 UTC, g2github commented on README.md
> +![alt_text](Reference_Images/cp4na-cd-prov-10.png "image_tooltip")
Fixed

2023-06-01 14:17 UTC, agopala95 commented on README.md
The image path on line 118 seems to be broken. Also, the image for the step "generate API key for the admin user through the CP4NA GUI", has it been uploaded?

2023-06-01 14:17 UTC, agopala95 commented on README.md
> +![alt_text](Reference_Images/cp4na-cd-prov-10.png "image_tooltip")
The image still seems to be the same here. Did you make the change in this line?

2023-06-01 14:22 UTC, agopala95 commented on README.md
>  }
This issue can be resolved by having the line here at 1007 end with closing the YAML part with three backticks without the spaces.

2023-06-01 14:30 UTC, agopala95 commented on README.md
>  }
Were the three backticks to close the YAML part added here after this line?
```suggestion
}
<3 backticks here>
```

2023-06-01 14:41 UTC, agopala95 commented on README.md
> +<3 backticks here>
````suggestion
```
````

2023-06-01 14:42 UTC, agopala95 commented on README.md
> +` ` `
````suggestion
```
````

2023-06-05 11:48 UTC, g2github commented on README.md
> +![alt_text](Reference_Images/cp4na-cpr-prov-8.png "image_tooltip")
corrected

2023-06-05 11:56 UTC, g2github commented on README.md
> +![alt_text](Reference_Images/cp4na-cd-prov-10.png "image_tooltip")
done

2023-06-05 12:08 UTC, g2github commented on README.md
> +<3 backticks here>
done

2023-06-12 15:13 UTC, agopala95 commented on README.md
Has this image been uploaded already? I see a broken link.

2023-06-12 15:14 UTC, agopala95 commented on README.md
> +1. Next, generate and take note of the API key for the user “admin” as seen in the screenshots below
Numbering typo - should be bullet 6?

2023-06-12 16:34 UTC, g2github commented on README.md
> +      1. Get the password for the default “admin” user of the CP4NA GUI by using the following command and then set access roles for the admin user in the GUI by first logging in with the obtained cr
It's 5 in my repo... 
[my repo]<img width="1786" alt="image" src="https://github.com/redhat-eets/cp4na/assets/7107832/882d6579-777e-4737-a311-4469a49d566d">

2023-06-12 16:52 UTC, g2github commented on README.md
relative path was wrong... fixed

2023-06-12 16:52 UTC, g2github commented on README.md
> +1. Next, generate and take note of the API key for the user “admin” as seen in the screenshots below
fixed

2023-06-12 16:52 UTC, g2github commented on README.md
> +      1. Get the password for the default “admin” user of the CP4NA GUI by using the following command and then set access roles for the admin user in the GUI by first logging in with the obtained cr
fixed

2023-06-12 17:12 UTC, agopala95 commented
Great work on the readme!

2023-06-12 17:12 UTC, merged